import { Module } from '@nestjs/common';
import { MigrateController } from './migrate.controller';
import { MigrateService } from './migrate.service';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CITYMASTER } from '../entity/entity/city-master.entity';
import { ACMASTER } from '../entity/entity/gl-account-master.entity';
import { ACCOHEAD } from '../entity/entity/gl-statement-code.entity';
import { ADVOCATEMASTER } from '../entity/entity/advocate-master.entity';
import { AUTHORITYMASTER } from '../entity/entity/authority-master.entity';
import { BANKMASTER } from '../entity/entity/bank-master.entity';
import { BRANCHMASTER } from '../entity/entity/clearing-branch-master.entity';
import { CASTMASTER } from '../entity/entity/cast-master.entity';
import { CATEGORYMASTER } from 'src/entity/entity/category-master.entity';
import { DEPRCATEGORY } from '../entity/entity/depriciation-category-master.entity';
import { DEPRRATE } from 'src/entity/entity/depriciation-rate-master.entity';
import { DIRECTORMASTER } from '../entity/entity/director-master.entity';
import { HOLIDAYSMASTER } from 'src/entity/entity/holiday.entity';
import { HEALTHMASTER } from 'src/entity/entity/health-master.entity';
import { INDUSTRYMASTER } from '../entity/entity/industry-master.entity';
import { INSUARANCEMASTER } from '../entity/entity/insurance-master.entity';
import { INTCATEGORYMASTER } from 'src/entity/entity/interest-category-master.entity';
import { INTRATESBPG } from 'src/entity/entity/saving-and-pigmy-interest-rates.entity';
import { ITEMMASTER } from 'src/entity/entity/dead-stock-master.entity';
import { LOANSTAGEMASTER } from '../entity/entity/loan-stage-master.entity';
import { NARRATIONMASTER } from '../entity/entity/narration.entity';
import { OCCUPATIONMASTER } from 'src/entity/entity/ocuupation-master.entity';
import { OPERATIONMASTER } from '../entity/entity/operation-master.entity';
import { PGCOMMISSIONMASTER } from 'src/entity/entity/PGCOMMISSIONMASTER.entity';
import { PRIORITYMASTER } from 'src/entity/entity/PRIORITYMASTER.entity';
import { PURPOSEMASTER } from 'src/entity/entity/purpose-master.entity';
import { REPORTTYPEMASTER } from '../entity/entity/report-type-master.entity';
import { SCHEMAST } from 'src/entity/entity/schemeParameters.entity';
import { IDMASTER } from 'src/entity/entity/customer-id.entity';
import { CUSTOMERADDRESS } from 'src/entity/entity/customer-address.entity';
import { SHMASTER } from 'src/entity/entity/share-master.entity';
import { DPMASTER } from 'src/entity/entity/dpmaster.entity';
import { LNMASTER } from '../entity/entity/term-loan-master.entity';
import { LNACINTRATE } from 'src/entity/entity/lnacintrate.entity';
import { GUARANTERDETAILS } from 'src/entity/entity/guarantor.entity';
import { PGMASTER } from 'src/entity/entity/pgmaster.entity';
import { ACCOTRAN } from 'src/entity/entity/accotran.entity';
import { DEPOTRAN } from '../entity/entity/depotran.entity';
import { LOANTRAN } from '../entity/entity/loantran.entity';
import { SHARETRAN } from '../entity/entity/sharetran.entity';
import { PIGMYTRAN } from '../entity/entity/pigmytran.entity';
import { HISTORYTRAN } from 'src/entity/entity/HISTORYTRAN.entity';
import { DAILYTRAN } from '../entity/entity/voucher.entity';
import { TRANINPUTHEAD } from 'src/entity/entity/transcation-input-gl-head-setting.entity';
import { HISTORYDIVIDEND } from 'src/entity/entity/shares-dividend.entity';
import { NOMINEELINK } from 'src/entity/entity/nominee.entity';
import { ATTERONEYLINK } from 'src/entity/entity/power-of-attorney.entity';
import { JointAcLink } from 'src/entity/entity/joint-account.entity';
import { TERMINTRATE } from 'src/entity/entity/rate-for term.entity';
import { INTRATETD } from '../entity/entity/interest-rate-for-term-deposit.entity';
import { INTRATETDMULTI } from '../entity/entity/deposit-intrest-rate.entity';
import { INTMULTI } from '../entity/entity/slab-int.entity';
import { INTRATELOAN } from '../entity/entity/interest-rate-for-loan-and-cc.entity';
import { LNCCLOAN } from '../entity/entity/loan-and-cc.entity';
import { INTRATEPATSCHEMES } from '../entity/entity/pat-scheme-interest-rates.entity';
import { INTRATE } from '../entity/entity/interest-rate.entity';
import { PREMATULESSRATE } from 'src/entity/entity/premature-pigmy-less-int-rate.entity';
import { PREMATULESS } from '../entity/entity/pigmy-less-int.entity';
import { SECURITYMASTER } from 'src/entity/entity/security-code.entity';
import { TDSRATE } from 'src/entity/entity/tds-interest-rate.entity';
import { SECURITYDETAILS } from 'src/entity/entity/security.entity';
import { COBORROWER } from 'src/entity/entity/coborrower.entity';
import { BANKDETAILS } from 'src/entity/entity/BANKDETAILS.entity';
import { COURTMASTER } from 'src/entity/entity/court-master.entity';
import { DOCUMENTMASTER } from 'src/entity/entity/document-master.entity';
import { ITEMCATEGORYMASTER } from '../entity/entity/item-category-master.entity';
import { LOCKERRACKMASTER } from 'src/entity/entity/locker-rack-master.entity';
import { LOCKERSIZE } from 'src/entity/entity/locker-size-master.entity';
import { LOCKERMASTER } from '../entity/entity/locker-rackwise-master.entity';
import { BALACATA } from '../entity/entity/minimum-balance-master.entity';
import { OWNBRANCHMASTER } from '../entity/entity/own-branch-master.entity';
import { PREFIX } from 'src/entity/entity/prefix-master.entity';
import { PRIORITYSECTORMASTER } from '../entity/entity/priority-sector-master.entity';
import { RECOVERYCLEARKMASTER } from 'src/entity/entity/recovery-cleark-master.entity';
import { RISKCATEGORYMASTER } from 'src/entity/entity/risk-category.entity';
import { SALARYDIVISIONMASTER } from 'src/entity/entity/salary-division-master.entity';
import { SUBSALARYMASTER } from '../entity/entity/sub-salary-division-master.entity';
import { WEAKERMASTER } from '../entity/entity/weaker-master.entity';
import { TDSFORMSUBMIT } from 'src/entity/entity/tds-form.entity';
import { NPAMASTER } from '../entity/entity/npa-classification.entity';
import { NPACLASSIFICATION } from 'src/entity/entity/npa-class.entity';
import { TDRECEIPTMASTER } from 'src/entity/entity/td-receipt-type.entity';
import { BOOKDEBTS } from '../entity/entity/book-debts.entity';
import { SECINSURANCE } from 'src/entity/entity/customer-insurance.entity';
import { FIREPOLICY } from 'src/entity/entity/fire-policy.entity';
import { FURNITURE } from 'src/entity/entity/furniture-and-fixture.entity';
import { GOLDSILVER } from 'src/entity/entity/gold-and-silver.entity';
import { GOVTSECULIC } from 'src/entity/entity/govt-security-and-lic.entity';
import { LANDBUILDING } from 'src/entity/entity/land-and-buildings.entity';
import { MARKETSHARE } from 'src/entity/entity/market-shares.entity';
import { OTHERSECURITY } from 'src/entity/entity/other-security.entity';
import { OWNDEPOSIT } from 'src/entity/entity/own-deposits.entity';
import { PLANTMACHINARY } from 'src/entity/entity/plant-and-machinery.entity';
import { PLEDGESTOCK } from '../entity/entity/pleadge-stock.entity';
import { STOCKSTATEMENT } from 'src/entity/entity/stock-statement.entity';
import { VEHICLE } from 'src/entity/entity/vehicle.entity';
import { RENEWALHISTORY } from '../entity/entity/RENEWALHISTORY.entity';
import { SYSPARA } from '../entity/entity/system-master-parameters.entity';
import { DIVPAIDTRAN } from '../entity/entity/DIVPAIDTRAN.entity';
import { INTINSTRUCTION } from '../entity/entity/interest-instruction.entity';
import { TODTRAN } from '../entity/entity/over-draft.entity';
import { SPECIALINSTRUCTION } from '../entity/entity/special-instruction.entity';
import { STANDINSTRUCTION } from 'src/entity/entity/standing-instruction.entity';
import { INTERESTTRAN } from 'src/entity/entity/INTERESTTRAN.entity'
import { COMMISSIONSLAB } from '../entity/entity/COMMISSIONSLAB.entity';
import { TEMPJOINTACLINK } from '../entity/entity/tempjointaclink.entity'
import { SIZEWISEBALANCE } from '../entity/entity/SIZEWISEBALANCE.entity'
import { TERMMASTER } from '../entity/entity/termmaster.entity'
import { AGENTCHANGEHISTORY } from '../entity/entity/AGENTCHANGEHISTORY.entity'
import { BANKBRANCHMASTER } from '../entity/entity/BANKBRANCHMASTER.entity'
import { BANKCOMMISSION } from '../entity/entity/BANKCOMMISSION.entity'
import { BANKDEPOTRAN } from '../entity/entity/BANKDEPOTRAN.entity'
import { BATCHVOUCHERTRAN } from '../entity/entity/BATCHVOUCHERTRAN.entity'
import { BUDGETMASTER } from '../entity/entity/BUDGETMASTER.entity'
import { CASHINTINSTRUCTIONS } from '../entity/entity/CASHINTINSTRUCTIONS.entity'
import { CDRATIO } from '../entity/entity/CDRATIO.entity'
import { CHARGES } from '../entity/entity/scheme-type-charges.entity'
import { CHARGESAMT } from '../entity/entity/charges.entity'
import { CHARGESNOTING } from '../entity/entity/CHARGESNOTING.entity'
import { DAILYSHRTRAN } from '../entity/entity/DAILYSHRTRAN.entity'
import { NPALOCK } from '../entity/entity/NPALOCK.entity'
import { EXCESSCASH } from '../entity/entity/EXCESSCASH.entity'
import { CRARTRAN } from '../entity/entity/CRARTRAN.entity'
import { DENOMINATION } from '../entity/entity/DENOMINATION.entity'
import { USERDENOMINATION } from '../entity/entity/USERDENOMINATION.entity'
import { SCHEMDATA } from '../entity/entity/SCHEMDATA.entity'
import { HISTORYDENO } from '../entity/entity/HISTORYDENO.entity'
import { HISTORYGENERALMEETING } from '../entity/entity/HISTORYGENERALMEETING.entity'
import { INTHISTORYTRAN } from '../entity/entity/INTHISTORYTRAN.entity'
import { TDSTRAN } from '../entity/entity/TDSTRAN.entity'
import { OIRTRAN } from '../entity/entity/OIRTRAN.entity'
import { RECOTRAN } from '../entity/entity/RECOTRAN.entity'
import { TDRECEIPTISSUE } from '../entity/entity/TDRECEIPTISSUE.entity'
import { STANDINSTRUCTIONLOG } from '../entity/entity/STANDINSTRUCTIONLOG.entity'
import { NPADATA } from '../entity/entity/NPADATA.entity'
import { INTINSTRUCTIONSLOG } from '../entity/entity/INTINSTRUCTIONSLOG.entity'
import { PASSBOOKPRINT } from '../entity/entity/PASSBOOKPRINT.entity'
import { PASSBOOKHISTORY } from '../entity/entity/PASSBOOKHISTORY.entity'
import { SUBSIDARYMASTER } from '../entity/entity/SUBSIDARYMASTER.entity'
import { MORATORIUMPERIOD } from '../entity/entity/moratorium-peroid-master.entity'
import { DEADSTOCKDETAIL } from '../entity/entity/DEADSTOCKDETAIL.entity'
import { DEADSTOCKHEADER } from '../entity/entity/DEADSTOCKHEADER.entity'
import { SHARECAPITALAMTDETAILS } from '../entity/entity/SHARECAPITALANTDETAILS.entity'
import { GLREPORTLINK } from '../entity/entity/GLREPORTLINK.entity'
import { GLREPORTMASTER } from '../entity/entity/GLREPORTMASTER.entity'
import { LOCKERTRAN } from '../entity/entity/LOCKERTRAN.entity'
import { LOCKERRENTTRAN } from '../entity/entity/LOCKERRENTTRAN.entity'
import { DEPOCLOSETRAN } from '../entity/entity/DEPOCLOSETRAN.entity'
import { DEPOCLOSETRANSAC } from '../entity/entity/DEPOCLOSETRANSAC.entity'
import { MANAGERVIEW } from '../entity/entity/manager-view-glp.entity'
import { DIVIDEND } from '../entity/entity/DIVIDEND.entity'
import { PIGMYCHARTMASTER } from '../entity/entity/pigmyChart.entity'
import { PIGMYCHART } from '../entity/entity/pigmy-chart.entity'
import { CUSTDOCUMENT } from '../entity/entity/document.entity'
@Module({
  imports: [TypeOrmModule.forFeature([SECURITYDETAILS, COBORROWER, ACMASTER, AUTHORITYMASTER, CITYMASTER, BANKMASTER, BRANCHMASTER, CASTMASTER, CATEGORYMASTER, DEPRCATEGORY, DEPRRATE, DIRECTORMASTER, HEALTHMASTER, HOLIDAYSMASTER, INDUSTRYMASTER, INSUARANCEMASTER, INTCATEGORYMASTER, INTRATESBPG, ITEMMASTER, LOANSTAGEMASTER, NARRATIONMASTER, OCCUPATIONMASTER, OPERATIONMASTER, PGCOMMISSIONMASTER, PRIORITYMASTER, PURPOSEMASTER, REPORTTYPEMASTER, SCHEMAST, IDMASTER, CUSTOMERADDRESS, SHMASTER, DPMASTER, LNMASTER, LNACINTRATE, JointAcLink, GUARANTERDETAILS, PGMASTER, ACCOTRAN, DEPOTRAN, LOANTRAN, SHARETRAN, PIGMYTRAN, HISTORYTRAN, ATTERONEYLINK, DAILYTRAN, TRANINPUTHEAD, HISTORYDIVIDEND, NOMINEELINK, TERMINTRATE, INTRATETD, INTRATETDMULTI, INTMULTI, INTRATELOAN, LNCCLOAN, INTRATEPATSCHEMES, INTRATE, PREMATULESSRATE, PREMATULESS, SECURITYMASTER, TDSRATE, ADVOCATEMASTER, BANKDETAILS, COURTMASTER, DOCUMENTMASTER, ITEMCATEGORYMASTER, LOCKERRACKMASTER, LOCKERSIZE, LOCKERMASTER, BALACATA, OWNBRANCHMASTER, PREFIX, PRIORITYSECTORMASTER, RECOVERYCLEARKMASTER, RISKCATEGORYMASTER, SALARYDIVISIONMASTER, SUBSALARYMASTER, WEAKERMASTER, TDSFORMSUBMIT, NPAMASTER, NPACLASSIFICATION, TDRECEIPTMASTER, BOOKDEBTS, SECINSURANCE, FIREPOLICY, FURNITURE, GOLDSILVER, GOVTSECULIC, LANDBUILDING, MARKETSHARE, OTHERSECURITY, OWNDEPOSIT, PLANTMACHINARY, PLEDGESTOCK, STOCKSTATEMENT, VEHICLE, RENEWALHISTORY, SYSPARA, DIVPAIDTRAN, INTINSTRUCTION, TODTRAN, SPECIALINSTRUCTION, STANDINSTRUCTION, INTERESTTRAN, COMMISSIONSLAB, TEMPJOINTACLINK, SIZEWISEBALANCE, TERMMASTER, AGENTCHANGEHISTORY, BANKBRANCHMASTER, BANKCOMMISSION, BANKDEPOTRAN, BATCHVOUCHERTRAN, BUDGETMASTER, CASHINTINSTRUCTIONS, CDRATIO, CHARGES, CHARGESAMT, CHARGESNOTING, DAILYSHRTRAN, NPALOCK, EXCESSCASH, CRARTRAN, DENOMINATION, USERDENOMINATION, SCHEMDATA, HISTORYDENO, HISTORYGENERALMEETING, INTHISTORYTRAN, TDSTRAN, OIRTRAN, MORATORIUMPERIOD, RECOTRAN, TDRECEIPTISSUE, STANDINSTRUCTIONLOG, NPADATA, INTINSTRUCTIONSLOG, PASSBOOKPRINT, PASSBOOKHISTORY, SUBSIDARYMASTER, DEADSTOCKDETAIL, DEADSTOCKHEADER, DEPOCLOSETRAN, DEPOCLOSETRANSAC, SHARECAPITALAMTDETAILS, MANAGERVIEW, GLREPORTLINK, GLREPORTMASTER, LOCKERTRAN, LOCKERRENTTRAN, DIVIDEND, PIGMYCHARTMASTER, PIGMYCHART, CUSTDOCUMENT])],
  controllers: [MigrateController],
  providers: [MigrateService]
})
export class MigrateModule { }
